name: pdx_airport
description: PDX Portland International Airport mobile app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  go_router: ^13.0.0
  cached_network_image: ^3.3.0
  flutter_dotenv: ^5.1.0
  http: ^1.2.0
  shimmer: ^3.0.0
  intl: ^0.19.0
  webview_flutter: ^4.4.0
  webview_flutter_web: ^0.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
